import React from "react";
import { useMap } from "../../shared/hooks/useMap";
import styles from "./LandUses.module.css";
const LandUses = () => {
    const { viewRef } = useMap();
    return (
        <div className="w-full h-full ">
            <div className={styles.color}>
                Landuse Map
            </div>
            <div
                ref={viewRef}
                className={`w-full h-full ${styles.map}`}
            ></div>
            <caption className={styles.caption}>
                landuse table
            </caption>
            <table className={styles.table}>
                <thead>
                    <tr>
                        <th>
                            Id
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Type
                        </th>
                        <th>
                            Shape_length
                        </th>
                        <th>
                            Shape_area
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            15
                        </td>
                        <td>
                            commercial
                        </td>
                        <td>
                            1500
                        </td>
                        <td>
                            184555
                        </td>
                        <td>
                            15742
                        </td>
                        <td>
                            15
                        </td>
                        <td>
                            commercial
                        </td>
                        <td>
                            1500
                        </td>
                        <td>
                            184555
                        </td>
                        <td>
                            15742
                        </td><td>
                            15
                        </td>
                        <td>
                            commercial
                        </td>
                        <td>
                            1500
                        </td>
                        <td>
                            184555
                        </td>
                        <td>
                            15742
                        </td><td>
                            15
                        </td>
                        <td>
                            commercial
                        </td>
                        <td>
                            1500
                        </td>
                        <td>
                            184555
                        </td>
                        <td>
                            15742
                        </td><td>
                            15
                        </td>
                        <td>
                            commercial
                        </td>
                        <td>
                            1500
                        </td>
                        <td>
                            184555
                        </td>
                        <td>
                            15742
                        </td><td>
                            15
                        </td>
                        <td>
                            commercial
                        </td>
                        <td>
                            1500
                        </td>
                        <td>
                            184555
                        </td>
                        <td>
                            15742
                        </td><td>
                            15
                        </td>
                        <td>
                            commercial
                        </td>
                        <td>
                            1500
                        </td>
                        <td>
                            184555
                        </td>
                        <td>
                            15742
                        </td><td>
                            15
                        </td>
                        <td>
                            commercial
                        </td>
                        <td>
                            1500
                        </td>
                        <td>
                            184555
                        </td>
                        <td>
                            15742
                        </td><td>
                            15
                        </td>
                        <td>
                            commercial
                        </td>
                        <td>
                            1500
                        </td>
                        <td>
                            184555
                        </td>
                        <td>
                            15742
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    );
};

export default LandUses;
